### ISSUE TITLE
size_tuple vs extents

### ISSUE THREAD

**Issue by prlw1** [BobSteagall/wg21#69]
Back already(!)

My second trivial program is
```
#include <linear_algebra.hpp>
#include <iostream>
#include <tuple>

int main()
{
        STD_LA::fs_matrix<double, 3, 3> R{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
        STD_LA::fs_vector<double, 3> v{{1, 2, 3}};
        auto x = R * v;
        std::cout << R(1,2) << '\n';
        std::cout << x(2) << '\n';
        std::cout << std::get<0>(R.size()) << '\n';
}

```
The aim is simply, given a matrix R, how do I find out the number of columns / rows.

According to `P1385R7.md`
```
    using size_tuple      = tuple<size_type, size_type>;
    constexpr size_tuple    size() const noexcept;
```
so I would expect `R.size()` to return a `tuple<size_type,size_type>`, and `get<0>` to return the first `size_type`.

This fails to compile with g++ 10.3.0:
```
c++  -O2 -fPIE -g -Werror -std=c++20     -I/usr/src/local/mdspan/include -I/usr/src/local/wg21/include  -c    wg21test.cc
wg21test.cc: In function ‘int main()’:
wg21test.cc:12:35: error: no matching function for call to ‘get<0>(std::math::matrix<std::math::fs_matrix_engine<double, 3, 3>, std::math::matrix_operation_traits>::index_tuple)’
   12 |  std::cout << std::get<0>(R.size()) << '\n';
      |                                   ^
...
/usr/src/local/mdspan/include/experimental/__p0009_bits/extents.hpp:206:3: note: candidate: ‘template<class IndexType>  requires  is_convertible_v<IndexType, std::experimental::extents<Extents ...>::index_type> constexpr std::experimental::extents<Extents>::extents(const std::array<IndexType, std::experimental::extents<Extents>::rank_dynamic()>&) [with IndexType = IndexType; long int ...Extents = {3, 3}]’
  206 |   extents(std::array<IndexType, rank_dynamic()> const& dyn) noexcept
      |   ^~~~~~~
```
As per #68, this is head `wg21`, and now 51b291a1265bf `mdspan`.

Have I maybe hit the R5 Feedback to do item
```
+ Use `extents` instead of `size_tuple`.
```
or am I missing something?

**Comment by Twon** [comment]
Yes, I think you will find that is out of date.  Most of the recent development has been taking places on the `r7y` branch with a view to being in line with the changes in the upcoming revision 7 of the specification: https://github.com/BobSteagall/wg21/tree/r7y

Please try against that branch and see if that improves things, just note that this branch is under development until the next paper revision is released.

**Comment by prlw1** [comment]
Thanks again!
```
cd /usr/src/local/wg21
git checkout r7y
```
did the trick, with the updated trivial program
```
#include <matrix.hpp>
#include <iostream>

int main()
{
        STD_LA::fixed_size_matrix<double, 3, 3> R{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
        STD_LA::fixed_size_column_vector<double, 3> v{1, 2, 3};
        auto x = R * v;
        std::cout << R(1,2) << '\n';
        std::cout << x(2) << '\n';
        std::cout << R.rows() << 'x' << R.columns() << '\n';
}
```

Might it be worth a note say in README.md to say that to try this out, one needs the r7y branch of this project, and the 9d1acac54305 commit of mdspan?

**Comment by Twon** [comment]
Yes, I can certainly update the readme to point to the `r7y` branch.  As for the 9d1acac54305 commit of mdspan, that is the revision hardcoded in the FetchContent call here on master: https://github.com/BobSteagall/wg21/blob/4b39067496f3a6401f6c76e965703de20c6622d7/CMakeLists.txt#L24

When you encountered the error with MDSpan were you attempting to build the `r7` branch?  I see that required change to the CMakeList.txt has not been back merged onto that branch...  I've opened the following issue to fix this properly on master and back merge the changes and should be able to look at this in the next day or so: https://github.com/BobSteagall/wg21/issues/70

**Comment by prlw1** [comment]
As explained in #68, I just checked out the 2 git repositories, and compiled the tiny program. Since then you have told me which branch and commit I should have checked out. These are header-only libraries, so no running of `cmake` needed. I just used `-I` to point the compiler to the relevant include directories. (For your amusement, as you asked for operating system / architecture, this is NetBSD/amd64 (!))

**Comment by Twon** [comment]
Oh wow, you are the first person to my knowledge to have built this on NetBSD/amd64 :)

Ah right, I had not taken in that you manually fetched both repositories.  If you had built the wg21 repo via CMake it would have fetched the correct MDSpan in the build directory, and then if you and ran the install step then it would have installed the correct MDspan and WG21 side by side.  This could have been achieve as such:
```
git clone git@github.com:BobSteagall/wg21.git
cd wg21
mkdir build
cd build

cmake ../ [-G <generator>] [configuration options] -DCMAKE_INSTALL_PREFIX=/usr/src/local/
cmake --build . --target install
```

Ok thanks, that's helpful for my understanding.

**Comment by Twon** [comment]
Closing for now as I think this is resolved, please reopen if you have further queries.
